### ISSUE TITLE
(v_data).scatter_(1, index_tensor, v_data.clone()))

### ISSUE THREAD

**Issue by insung3511** [insung3511/ecg-dbn#1]
I'm stuck in problem on RBM.py line 78. That part is multiply of matrix, tensors that for positive way. But I think this issue is a data type problem. Code of issue part is this.
```python
        stats_pos = torch.matmul(h_prob_pos,
                                (v_data).scatter_(1, index_tensor, v_data.clone()))
```
and error is...
```
Traceback (most recent call last):
  File "/Users/bahk_insung/Documents/Github/ecg-dbn/model.py", line 41, in <module>
    error = bbrbm.cd(train_temp_data)
  File "/Users/bahk_insung/Documents/Github/ecg-dbn/BBRBM.py", line 27, in cd
    return RBMBase.cd(self, v_data, k, eta, alpha, lam)
  File "/Users/bahk_insung/Documents/Github/ecg-dbn/RBM.py", line 78, in cd
    (v_data).scatter_(1, index_tensor, v_data.clone()))
RuntimeError: index 1 is out of bounds for dimension 1 with size 1
```

Still workin solve and anyone know about this problem, please comment on my issue. Thank you :D

**Comment by insung3511** [comment]
Get back to same previous problem. You can see that I committed message I always stuck in this error.
```
RuntimeError: inconsistent tensor size, expected tensor [80] and src [180] to have the same number of elements, but got 80 and 180 elements respectively
```
I matched dimension and matrix multiply problem are solved but I think data type issue.

**Comment by insung3511** [comment]
Aight, I solved the stats_pos matmul part. But same problem at stats_neg 😂😂😂
WIP now, and I will commenting for my status.

**Comment by insung3511** [comment]
All solved problem with stats_pos and stats_neg. Each of stats positive and negative was same input parameter types and size were unmatched.

If you want more specific describe send email or contact to me.
